# Generated by Django 5.2.8 on 2025-11-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
