# Generated by Django 5.2.8 on 2025-11-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Отправлена'), ('processing', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.benefit')),
            ],
        ),
    ]
