# Generated by Django 5.2.8 on 2025-11-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст новости')),
                ('source_url', models.URLField(verbose_name='Ссылка на источник')),
                ('source_name', models.CharField(max_length=200, verbose_name='Название источника')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
    ]
