# Generated by Django 5.2.8 on 2025-11-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_targetgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='target_groups',
        ),
        migrations.AddField(
            model_name='benefit',
            name='target_groups',
            field=models.ManyToManyField(related_name='benefits', to='benefits.targetgroup'),
        ),
    ]
