# Generated by Django 5.2.8 on 2025-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_benefit_is_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='type',
            field=models.CharField(choices=[('federal', 'Федераральная'), ('regional', 'Региональная'), ('municipal', 'Муниципальная'), ('commercial', 'Коммерческая')], max_length=20),
        ),
    ]
