# Generated by Django 5.2.8 on 2025-11-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_add_commercial_benefit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании-спонсора'),
        ),
    ]
