# Generated by Django 5.2.8 on 2025-11-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0007_benefit_sponsor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='sponsor_name',
        ),
    ]
